public enum ExceptionLocation {
    case CORE_INITIALIZE
    case CHAT_START_LISTENERS
    case CHAT_OPEN
    case CHAT_SET_DEPARTMENT
    case CHAT_SET_LANGUAGE
    case CHAT_SET_ADDITIONAL_INFORMATION
    case CHAT_SET_PAGE_TITLE
    case CHAT_SET_QUESTION
    case CHAT_GET_DEPARTMENTS
    case CHAT_END_SESSION
    case NOTIFICATION_ENABLE_PUSH
    case NOTIFICATION_HANDLE_NOTIFICATION
    case NOTIFICATION_IS_ZOHO_NOTIFICATION
    case DEPARTMENT_GET_ALL
    case DEPARTMENT_GET_DEFAULT
    case DEPARTMENT_GET_BY_COUNTRY
}
